name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install norminette

    - name: Run 42 Norminette in src folder (excluding mlx directory)
      run: |
        find src -type d -name 'mlx' -prune -o -name '*.c' -exec norminette {} \; > norm_output.txt

    - name: Run merge check script
      run: bash .github/merge_check.sh
